### ISSUE TITLE
[Bug] Failing uniqueness test on `stg_hubspot__property`

### ISSUE THREAD

**Issue by kcraig-ats** [fivetran/dbt_hubspot_source#139]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the issue

I have recently encountered a uniqueness failure on `stg_hubspot__property._fivetran_id`. I reached out to Fivetran support to understand how this key was generated and it was suggested that we use `_fivetran_id` and `hubspot_object` as a composite key. 

### Relevant error log or model output

```shell

```

### Expected behavior

I expect `stg_hubspot__property` to have a unique key.

### Possible solution

```yml
# models/stg_hubspot__property.yml

  - name: stg_hubspot__property
    description: Each record represents a property.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - _fivetran_id
            - hubspot_object
```

### dbt Project configurations

  hubspot_email_event_forward_enabled: false
  hubspot_email_event_print_enabled: false
  hubspot_email_event_spam_report_enabled: false
  hubspot_service_enabled: false
  hubspot_contact_property_enabled: false
  hubspot__pass_through_all_columns: true

### Package versions

[">=0.22.0", "<0.23.0"]

### What database are you using dbt with?

redshift

### How are you running this dbt package?

dbt Cloud™

### dbt Version

1.8

### Are you willing to open a PR to help address this issue?

- [x] Yes.
- [ ] Yes, but I will need assistance.
- [ ] No.
