### ISSUE TITLE
[Bug] stg_hubspot__deal_contact is nowhere to be found

### ISSUE THREAD

**Issue by dietofworms** [fivetran/dbt_hubspot_source#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In the ERD provided by Fivetran [1] there is a model for `deal_contact` but we can't see this anywhere in the package or this repo. 

[1] https://docs.google.com/presentation/d/1KABQnt8WmtZe7u5l7WFUoPIsWzv63P9gsWF79XGLoZE/edit#slide=id.gd207c04e3c_4_5

### Expected behavior

The model file exists in the package

### dbt Project configurations

```yml
models:
  hubspot_source:
    +schema: staging

...
vars:
  # Hubspot source package config
  hubspot_database: raw
  hubspot_schema: hubspot_fivetran
...
```

### Package versions

```yml
  - package: fivetran/hubspot_source
    version: [">=0.5.0", "<0.6.0"]

```

### What database are you using dbt with?

snowflake

### dbt Version

snowflake: 1.0.1

### Are you willing to open a PR to help address this issue?

- [x] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
