### ISSUE TITLE
Managing source freshness snapshots

### ISSUE THREAD

**Issue by dom-in-ic-g** [fivetran/dbt_hubspot_source#8]
We've turned off one of the tables in the fivetran connector (contact_property_history) because the MAR is quite high.
This causes the freshness snapshots to fail in dbt cloud.
dbt doesn't currently(17.1) let you provide arguments to exclude from freshness snapshots you either have to be explicit in the command or use default(all sources)

We don't want to disable the downstream models from this table, we're just happy to have some fields out of date.
Unfortunately the only parameter we can set to avoid this also disables the engagements models.

It might be useful to have a way to turn off sources in dbt_project.yml similar to how other variables work in the package.

Current
```
      - name: contact_property_history
        freshness:
          warn_after: {count: 84, period: hour}
          error_after: {count: 168, period: hour}
```

Preferred outcome
```
      - name: contact_property_history
        freshness: null
```
